swagger: '2.0'
info:
  title: Social media monitoring
  version: 1.0.0
tags:
  - name: posts
paths:
  /posts:
    get:
      tags:
        - posts
      operationId: getPosts
      parameters:
        - name: count
          in: query
          description: "количество записей, которое необходимо получить. Максимально\
          е значение 100"
          required: true
          maximum: 100
          minimum: 0
          type: integer
        - name: domains
          in: body
          schema:
            title: domains
            type: array
            items:
              type: string
        - name: filter
          in: query
          description: "определяет, какие типы записей на стене необходимо получить\
          . Возможные значения"
          required: false
          type: string
          enum:
            - suggests
            - postponed
            - owner
            - others
            - all
      responses:
        200:
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Post'
            x-content-type: application/json
definitions:
  Post:
    type: object
    required: [ "count", "items" ]
    properties:
      count:
        type: integer
      items:
        type: array
        items:
          $ref: '#/definitions/WallPost'
    example:
      count: 0
      items:
        - date: 5
          from_id: 5
          owner_id: 1
          id: 6
          text: text
        - date: 5
          from_id: 5
          owner_id: 1
          id: 6
          text: text
  WallPost:
    type: object
    required: ["id", "owner_id", "from_id", "date"]
    properties:
      id:
        type: integer
      owner_id:
        type: integer
      from_id:
        type: integer
      date:
        type: integer
      text:
        type: string
    example:
      date: 5
      from_id: 5
      owner_id: 1
      id: 6
      text: text

