openapi: 3.0.1
info:
  title: Social media monitoring
  version: 1.0.0
servers:
- url: /
tags:
- name: posts
paths:
  /posts:
    get:
      operationId: getPosts
      parameters:
      - description: количество записей, которое необходимо получить. Максимальное
          значение 100
        in: query
        name: count
        required: true
        schema:
          maximum: 100
          minimum: 0
          type: integer
      - description: определяет, какие типы записей на стене необходимо получить.
          Возможные значения
        in: query
        name: filter
        schema:
          enum:
          - suggests
          - postponed
          - owner
          - others
          - all
          type: string
      requestBody:
        content:
          '*/*':
            schema:
              items:
                type: string
              title: domains
              type: array
        required: false
      responses:
        "200":
          content:
            '*/*':
              schema:
                items:
                  $ref: '#/components/schemas/Post'
                type: array
          description: successful operation
      tags:
      - posts
      x-codegen-request-body-name: domains
components:
  schemas:
    Post:
      example:
        count: 0
        items:
        - date: 5
          from_id: 5
          owner_id: 1
          id: 6
          text: text
        - date: 5
          from_id: 5
          owner_id: 1
          id: 6
          text: text
      properties:
        count:
          type: integer
        items:
          items:
            $ref: '#/components/schemas/WallPost'
          type: array
      required:
      - count
      - items
      type: object
    WallPost:
      example:
        date: 5
        from_id: 5
        owner_id: 1
        id: 6
        text: text
      properties:
        id:
          type: integer
        owner_id:
          type: integer
        from_id:
          type: integer
        date:
          type: integer
        text:
          type: string
      required:
      - date
      - from_id
      - id
      - owner_id
      type: object
x-original-swagger-version: "2.0"
